[package]
name = "capstone_test"
version = "0.1.0"
edition = "2021"

[dependencies]
capstone = "0.12.0"
xmas-elf = "0.9.1"
ratatui = { version = "0.26.3", features = [ "crossterm" ] }
crossterm = "0.27.0"
object = "0.36.0"
keystone-engine = "0.1.0"
